.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PCSC_SCAN 1 "April 10, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pcsc_scan \- regularly scans every PC/SC readers connected to the host
.SH SYNOPSIS
.BI "pcsc_scan [" options ]
.SH DESCRIPTION
This manual page documents the
.B pcsc_scan
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBpcsc_scan\fP is a program that regularly scans every PC/SC readers
connected to the host and display the status of the cards inserted in
the readers.

The normal way to exit the program is to use Control-C.

When \fBpcsc_scan\fP is started it asks \fBPC/SC layer\fP the list of
available smart card readers. The list is printed. A sequence number is
printed before each reader.

Example:
 PC/SC device scanner
 V 1.4.27 (c) 2001-2017, Ludovic Rousseau
 Scanning present readers...
 0: Gemalto PC Twin Reader

When a card is inserted in any reader some information is printed:
.TP
date and time:
Wed Apr 12 14:25:30 2017
.TP
reader name:
Reader 0: Gemalto PC Twin Reader
.TP
card state and occurred event:
Card state: Card inserted,
.TP
ATR in case of card insertion:
ATR: 3B 82 00 86 1E
.TP
print an ATR analysis if the \fBATR_analysis\fP command is available:
 ATR: 3B 82 00 86 1E
 + TS = 3B --> Direct Convention
 + T0 = 82, Y(1): 1000, K: 2 (historical bytes)
   TD(1) = 00 --> Y(i+1) = 0000, Protocol T = 0
 -----
 + Historical bytes: 86 1E
.SH OPTIONS
.TP
.B \-h
print help
.TP
.B \-V
print version number
.TP
.B \-n
do not print ATR analysis.
Use this option if \fBATR_analysis\fP is not available for example.
.TP
.B \-r
prints the list of readers and then exits.
.TP
.B \-s
stress mode. Sends APDU commands to the card indefinitely (until the
card or the reader is removed).
.TP
.B \-t secs
specify time program should run, in seconds. The program will terminate when this
time has passed.
.TP
.B \-q
quiet: prints minimal messages.
.TP
.B \-v
verbose: prints additional messages (default).
.SH SEE ALSO
.BR pcscd "(8), " ATR_analysis (1)
.SH AUTHOR
Ludovic Rousseau <ludovic.rousseau@free.fr>
