name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            autoconf
            autoconf-archive
            automake
            make
            pkg-config
          pacboy: >-
            gcc:p
            gettext:p

      - uses: actions/checkout@v4

      - name: compile
        run: |
          ./bootstrap
          ./configure
          make V=1
